In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('mission_launches.csv')
print(data)

      Unnamed: 0.1  Unnamed: 0 Organisation  \
0                0           0       SpaceX
1                1           1         CASC
2                2           2       SpaceX
3                3           3    Roscosmos
4                4           4          ULA
...            ...         ...          ...
4319          4319        4319      US Navy
4320          4320        4320         AMBA
4321          4321        4321      US Navy
4322          4322        4322    RVSN USSR
4323          4323        4323    RVSN USSR

                                               Location  \
0            LC-39A, Kennedy Space Center, Florida, USA
1     Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...
2                         Pad A, Boca Chica, Texas, USA
3          Site 200/39, Baikonur Cosmodrome, Kazakhstan
4              SLC-41, Cape Canaveral AFS, Florida, USA
...                                                 ...
4319           LC-18A, Cape Canaveral AFS, Florida, USA
4320           LC-26A, Cape Canaveral AFS, Florida, USA
4321           LC-18A, Cape Canaveral AFS, Florida, USA
4322          Site 1/5, Baikonur Cosmodrome, Kazakhstan
4323          Site 1/5, Baikonur Cosmodrome, Kazakhstan

                            Date  \
0     Fri Aug 07, 2020 05:12 UTC
1     Thu Aug 06, 2020 04:01 UTC
2     Tue Aug 04, 2020 23:57 UTC
3     Thu Jul 30, 2020 21:25 UTC
4     Thu Jul 30, 2020 11:50 UTC
...                          ...
4319  Wed Feb 05, 1958 07:33 UTC
4320  Sat Feb 01, 1958 03:48 UTC
4321  Fri Dec 06, 1957 16:44 UTC
4322  Sun Nov 03, 1957 02:30 UTC
4323  Fri Oct 04, 1957 19:28 UTC

                                            Detail  Rocket_Status  Price  \
0     Falcon 9 Block 5 | Starlink V1 L9 & BlackSky   StatusActive   50.0
1              Long March 2D | Gaofen-9 04 & Q-SAT   StatusActive  29.75
2               Starship Prototype | 150 Meter Hop   StatusActive    NaN
3     Proton-M/Briz-M | Ekspress-80 & Ekspress-103   StatusActive   65.0
4                       Atlas V 541 | Perseverance   StatusActive  145.0
...                                            ...            ...    ...
4319                     Vanguard | Vanguard TV3BU  StatusRetired    NaN
4320                           Juno I | Explorer 1  StatusRetired    NaN
4321                       Vanguard | Vanguard TV3  StatusRetired    NaN
4322                    Sputnik 8K71PS | Sputnik-2  StatusRetired    NaN
4323                    Sputnik 8K71PS | Sputnik-1  StatusRetired    NaN

     Mission_Status
0           Success
1           Success
2           Success
3           Success
4           Success
...             ...
4319        Failure
4320        Success
4321        Failure
4322        Success
4323        Success

[4324 rows x 9 columns]

In [3]:
data.shape

(4324, 9)

In [4]:
data.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Organisation', 'Location', 'Date',
       'Detail', 'Rocket_Status', 'Price', 'Mission_Status'],
      dtype='object')

In [6]:
data.head(5)

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145.0,Success

In [11]:
data.isna()

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
4319,False,False,False,False,False,False,False,True,False
4320,False,False,False,False,False,False,False,True,False
4321,False,False,False,False,False,False,False,True,False
4322,False,False,False,False,False,False,False,True,False
4323,False,False,False,False,False,False,False,True,False

In [12]:
data_1 = data.dropna()
data_1

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145.0,Success
5,5,5,CASC,"LC-9, Taiyuan Satellite Launch Center, China","Sat Jul 25, 2020 03:13 UTC","Long March 4B | Ziyuan-3 03, Apocalypse-10 & N...",StatusActive,64.68,Success
...,...,...,...,...,...,...,...,...,...
3855,3855,3855,US Air Force,"SLC-4W, Vandenberg AFB, California, USA","Fri Jul 29, 1966 18:43 UTC",Titan IIIB | KH-8,StatusRetired,59.0,Success
3971,3971,3971,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA","Thu May 06, 1965 15:00 UTC",Titan IIIA | LES 2 & LCS 1,StatusRetired,63.23,Success
3993,3993,3993,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA","Thu Feb 11, 1965 15:19 UTC",Titan IIIA | LES 1,StatusRetired,63.23,Success
4000,4000,4000,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA","Thu Dec 10, 1964 16:52 UTC",Titan IIIA | Transtage 2,StatusRetired,63.23,Success
4020,4020,4020,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA","Tue Sep 01, 1964 15:00 UTC",Titan IIIA | Transtage 1,StatusRetired,63.23,Failure

In [16]:
data_1["Date"] = pd.to_datetime(data_1["Date"], utc=True ,format="mixed")
data_1

/tmp/ipykernel_2982/1646510514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1["Date"] = pd.to_datetime(data_1["Date"], utc=True ,format="mixed")

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.0,Success
5,5,5,CASC,"LC-9, Taiyuan Satellite Launch Center, China",2020-07-25 03:13:00+00:00,"Long March 4B | Ziyuan-3 03, Apocalypse-10 & N...",StatusActive,64.68,Success
...,...,...,...,...,...,...,...,...,...
3855,3855,3855,US Air Force,"SLC-4W, Vandenberg AFB, California, USA",1966-07-29 18:43:00+00:00,Titan IIIB | KH-8,StatusRetired,59.0,Success
3971,3971,3971,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1965-05-06 15:00:00+00:00,Titan IIIA | LES 2 & LCS 1,StatusRetired,63.23,Success
3993,3993,3993,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1965-02-11 15:19:00+00:00,Titan IIIA | LES 1,StatusRetired,63.23,Success
4000,4000,4000,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1964-12-10 16:52:00+00:00,Titan IIIA | Transtage 2,StatusRetired,63.23,Success
4020,4020,4020,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1964-09-01 15:00:00+00:00,Titan IIIA | Transtage 1,StatusRetired,63.23,Failure

In [17]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 4020
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    964 non-null    int64
 1   Unnamed: 0      964 non-null    int64
 2   Organisation    964 non-null    object
 3   Location        964 non-null    object
 4   Date            964 non-null    datetime64[ns, UTC]
 5   Detail          964 non-null    object
 6   Rocket_Status   964 non-null    object
 7   Price           964 non-null    object
 8   Mission_Status  964 non-null    object
dtypes: datetime64[ns, UTC](1), int64(2), object(6)
memory usage: 75.3+ KB

In [18]:
data_1['Price'] = data_1['Price'].str.replace("$","")
data_1['Price'] = data_1['Price'].str.replace(",","")

/tmp/ipykernel_2982/3724249417.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['Price'] = data_1['Price'].str.replace("$","")
/tmp/ipykernel_2982/3724249417.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['Price'] = data_1['Price'].str.replace(",","")

In [19]:
data_1

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.0,Success
5,5,5,CASC,"LC-9, Taiyuan Satellite Launch Center, China",2020-07-25 03:13:00+00:00,"Long March 4B | Ziyuan-3 03, Apocalypse-10 & N...",StatusActive,64.68,Success
...,...,...,...,...,...,...,...,...,...
3855,3855,3855,US Air Force,"SLC-4W, Vandenberg AFB, California, USA",1966-07-29 18:43:00+00:00,Titan IIIB | KH-8,StatusRetired,59.0,Success
3971,3971,3971,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1965-05-06 15:00:00+00:00,Titan IIIA | LES 2 & LCS 1,StatusRetired,63.23,Success
3993,3993,3993,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1965-02-11 15:19:00+00:00,Titan IIIA | LES 1,StatusRetired,63.23,Success
4000,4000,4000,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1964-12-10 16:52:00+00:00,Titan IIIA | Transtage 2,StatusRetired,63.23,Success
4020,4020,4020,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1964-09-01 15:00:00+00:00,Titan IIIA | Transtage 1,StatusRetired,63.23,Failure

In [20]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 4020
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    964 non-null    int64
 1   Unnamed: 0      964 non-null    int64
 2   Organisation    964 non-null    object
 3   Location        964 non-null    object
 4   Date            964 non-null    datetime64[ns, UTC]
 5   Detail          964 non-null    object
 6   Rocket_Status   964 non-null    object
 7   Price           964 non-null    object
 8   Mission_Status  964 non-null    object
dtypes: datetime64[ns, UTC](1), int64(2), object(6)
memory usage: 75.3+ KB

In [21]:
data_1['Price'] = pd.to_numeric(data_1['Price'])

/tmp/ipykernel_2982/4125573115.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_1['Price'] = pd.to_numeric(data_1['Price'])

In [22]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 4020
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    964 non-null    int64
 1   Unnamed: 0      964 non-null    int64
 2   Organisation    964 non-null    object
 3   Location        964 non-null    object
 4   Date            964 non-null    datetime64[ns, UTC]
 5   Detail          964 non-null    object
 6   Rocket_Status   964 non-null    object
 7   Price           964 non-null    float64
 8   Mission_Status  964 non-null    object
dtypes: datetime64[ns, UTC](1), float64(1), int64(2), object(5)
memory usage: 75.3+ KB

In [29]:
group_1 = data_1.groupby('Organisation')
group_1.value_counts()

Organisation  Unnamed: 0.1  Unnamed: 0  Location                                                 Date                       Detail                                             Rocket_Status  Price  Mission_Status
Arianespace   40            40          Site 31/6, Baikonur Cosmodrome, Kazakhstan               2020-03-21 17:06:00+00:00  Soyuz 2.1b/Fregat | OneWeb #3                      StatusActive   48.5   Success           1
              48            48          ELA-3, Guiana Space Centre, French Guiana, France        2020-02-18 22:18:00+00:00  Ariane 5 ECA | JCSAT-17 & GEO-KOMPSAT 2B           StatusActive   200.0  Success           1
              54            54          Site 31/6, Baikonur Cosmodrome, Kazakhstan               2020-02-06 21:42:00+00:00  Soyuz 2.1b/Fregat | OneWeb #2                      StatusActive   48.5   Success           1
              58            58          ELA-3, Guiana Space Centre, French Guiana, France        2020-01-16 21:05:00+00:00  Ariane 5 ECA | Eutelsat Konnect BB4A & GSAT-30     StatusActive   200.0  Success           1
              81            81          ELA-3, Guiana Space Centre, French Guiana, France        2019-11-26 21:23:00+00:00  Ariane 5 ECA | Inmarsat 5 F5 & TIBA-1              StatusActive   200.0  Success           1
                                                                                                                                                                                                                      ..
VKS RF        764           764         Site 133/3, Plesetsk Cosmodrome, Russia                  2009-07-06 01:26:00+00:00  Rokot/Briz KM | Cosmos 2451 to 2453                StatusRetired  41.8   Success           1
              819           819         Site 133/3, Plesetsk Cosmodrome, Russia                  2008-05-23 15:20:00+00:00  Rokot/Briz KM | Cosmos 2437 to 2439, Youbilielnyi  StatusRetired  41.8   Success           1
              948           948         Site 133/3, Plesetsk Cosmodrome, Russia                  2005-08-26 18:34:00+00:00  Rokot/Briz KM | Monitor-E                          StatusRetired  41.8   Success           1
              979           979         Site 43/4, Plesetsk Cosmodrome, Russia                   2004-11-08 18:29:00+00:00  Soyuz 2.1a | Demo Flight                           StatusActive   48.5   Success           1
Virgin Orbit  27            27          Cosmic Girl, Mojave Air and Space Port, California, USA  2020-05-25 19:50:00+00:00  LauncherOne | Demo Flight                          StatusActive   12.0   Failure           1
Name: count, Length: 964, dtype: int64

In [30]:
spending_analysis = group_1['Price'].sum().sort_values(ascending=False)
spending_analysis

Organisation
NASA               76280.00
Arianespace        16345.00
ULA                14798.00
RVSN USSR          10000.00
CASC                6340.26
SpaceX              5444.00
Northrop            3930.00
MHI                 3532.50
ISRO                2177.00
US Air Force        1550.92
VKS RF              1548.90
ILS                 1320.00
Boeing              1241.00
Roscosmos           1187.50
Martin Marietta      721.40
Kosmotras            638.00
Eurockot             543.40
Lockheed             280.00
JAXA                 168.00
Rocket Lab            97.50
ESA                   37.00
ExPace                28.30
EER                   20.00
Sandia                15.00
Virgin Orbit          12.00
Name: Price, dtype: float64

In [31]:
spending_df = spending_analysis.reset_index()
spending_df.columns = ['Organisation', 'Total_Spending']

In [32]:
spending_df

       Organisation  Total_Spending
0              NASA        76280.00
1       Arianespace        16345.00
2               ULA        14798.00
3         RVSN USSR        10000.00
4              CASC         6340.26
5            SpaceX         5444.00
6          Northrop         3930.00
7               MHI         3532.50
8              ISRO         2177.00
9      US Air Force         1550.92
10           VKS RF         1548.90
11              ILS         1320.00
12           Boeing         1241.00
13        Roscosmos         1187.50
14  Martin Marietta          721.40
15        Kosmotras          638.00
16         Eurockot          543.40
17         Lockheed          280.00
18             JAXA          168.00
19       Rocket Lab           97.50
20              ESA           37.00
21           ExPace           28.30
22              EER           20.00
23           Sandia           15.00
24     Virgin Orbit           12.00

In [39]:
import plotly.express as px

In [42]:
fig = px.treemap(spending_df,path=["Organisation"],values="Total_Spending",title='Total Space Mission Spending by Organization',
                 color='Total_Spending',
                 color_continuous_scale='Viridis')
fig.show()

In [43]:
data_1['Country'] = data_1['Location'].str.split(',').str[-1].str.strip()
data_1['Country'].value_counts()

/tmp/ipykernel_2982/240398949.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Country
USA                               487
China                             158
France                             95
India                              67
Russia                             54
Kazakhstan                         46
Japan                              40
New Zealand                        13
Gran Canaria                        2
Yellow Sea                          1
Pacific Missile Range Facility      1
Name: count, dtype: int64

In [44]:
data_1

,Unnamed: 0.1,Unnamed: 0,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status,Country
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success,USA
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,China
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success,Kazakhstan
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success,USA
5,5,5,CASC,"LC-9, Taiyuan Satellite Launch Center, China",2020-07-25 03:13:00+00:00,"Long March 4B | Ziyuan-3 03, Apocalypse-10 & N...",StatusActive,64.68,Success,China
...,...,...,...,...,...,...,...,...,...,...
3855,3855,3855,US Air Force,"SLC-4W, Vandenberg AFB, California, USA",1966-07-29 18:43:00+00:00,Titan IIIB | KH-8,StatusRetired,59.00,Success,USA
3971,3971,3971,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1965-05-06 15:00:00+00:00,Titan IIIA | LES 2 & LCS 1,StatusRetired,63.23,Success,USA
3993,3993,3993,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1965-02-11 15:19:00+00:00,Titan IIIA | LES 1,StatusRetired,63.23,Success,USA
4000,4000,4000,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1964-12-10 16:52:00+00:00,Titan IIIA | Transtage 2,StatusRetired,63.23,Success,USA
4020,4020,4020,US Air Force,"SLC-20, Cape Canaveral AFS, Florida, USA",1964-09-01 15:00:00+00:00,Titan IIIA | Transtage 1,StatusRetired,63.23,Failure,USA

In [56]:
country_map = {
    'Russian Federation': 'Russia',
    'Kazakhstan': 'Russia',
    'New Mexico': 'USA',
    'Yellow Sea': 'China',
    'Shahrud Missile Test Site': 'Iran',
    'Pacific Ocean': 'USA'
}
data_1['Country'] = data_1['Country'].replace(country_map)

/tmp/ipykernel_2982/2127622725.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [55]:
country_launches = data_1['Country'].value_counts().reset_index()
country_launches.columns = ['Country', 'Launches']
fig = px.choropleth(country_launches,
                    locations="Country",
                    locationmode='country names',
                    color="Launches",
                    hover_name="Country",
                    title='Number of Space Launches by Country',
                    color_continuous_scale=px.colors.sequential.Plasma)
fig.show()

In [47]:
launch = px.sunburst(data_1, path=['Organisation', 'Mission_Status'], values='Price')
launch.show()

In [48]:
data_1['Year'] = data_1['Date'].dt.year
data_1['Month'] = data_1['Date'].dt.month_name()

/tmp/ipykernel_2982/1070222521.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_2982/1070222521.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [54]:
launches_per_year = data_1.groupby(['Year', 'Organisation']).size().reset_index(name='Count')

fig = px.line(launches_per_year,
              x='Year',
              y='Count',
              color='Organisation',
              title='Number of Launches per Year by Organisation')
fig.show()

In [53]:
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']
month_counts = data_1['Month'].value_counts().reset_index()
month_counts.columns = ['Month', 'Count']

fig = px.bar(month_counts,
             x='Month',
             y='Count',
             title='Most Popular Months for Space Launches',
             category_orders={'Month': month_order})
fig.show()

In [52]:
data_1.to_csv('Space_Missions_Cleaned.csv', index=False)